// src/components/modal/confirmModal/ConfirmModal.vue
<template>
  <transition name="modal">
    <div :class="css.modalMask" @click="$emit('close')">
      <div :class="css.modalWrapper">
        <div :class="css.modalContainer" @click.stop>
          <div :class="css.modalHeader">
            <slot name="header">
              <h3>Confirm your action</h3>
            </slot>
          </div>

          <div :class="css.modalBody">
            <slot name="body">
              Please confirm your action
            </slot>
          </div>

          <div :class="css.modalFooter">
            <slot name="footer">
              <button :class="css.modalButtonLeft" @click="$emit('close')">
                Close
              </button>
              <button :class="css.modalButtonRight" @click="$emit('confirm')">
                Confirm
              </button>
            </slot>
          </div>
        </div>
      </div>
    </div>
  </transition>
</template>

<script>
import css from "./ConfirmModal.module.css";

export default {
  data() {
    return {
      css,
    };
  },
  methods: {},
};
</script>

// apps/web/app/components/ConfirmModal/ConfirmModal.tsx
import type { ReactNode } from 'react'
import css from './ConfirmModal.module.css'

interface ConfirmModalProps {
  children?: ReactNode
  onClose: () => void
  onConfirm: () => void
}

export default function ConfirmModal({
  children,
  onClose,
  onConfirm,
}: ConfirmModalProps) {
  return (
    <div className={css.modalMask} onClick={onClose}>
      <div className={css.modalWrapper}>
        <div className={css.modalContainer} onClick={(e) => e.stopPropagation()}>
          <div className={css.modalHeader}>
            <h3>Confirm your action</h3>
          </div>

          <div className={css.modalBody}>
            {children || 'Please confirm your action'}
          </div>

          <div className={css.modalFooter}>
            <button className={css.modalButtonLeft} onClick={onClose}>
              Close
            </button>
            <button className={css.modalButtonRight} onClick={onConfirm}>
              Confirm
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
