// src/App.vue
<template>
  <div class="appContainer">
    <GlobalEvents
      @visibilitychange="onPageVisibilityChange"
      @mousemove="handlePageMouseMove"
      @mouseenter="handlePageMouseEnter"
      @mouseleave="handlePageMouseLeave"
      @mouseout="handlePageMouseOut"
      @dragenter.prevent
      @dragover.prevent
      @drop="handlePageDrop"
      @paste="handleGlobalPasteEvent"
      @keyup.shift.s="onPlaylistShuffle"
      @keyup.left="playlistPrevious"
      @keyup.right="playlistNext"
      @keyup.esc="handleShowPlaying"
      @keyup.49="handleUpcomingSelected(1)"
      @keyup.50="handleUpcomingSelected(2)"
      @keyup.51="handleUpcomingSelected(3)"
      @keyup.80="handleShowPlaylist"
      @keyup.shift.191="handleShowHelp"
    />

    <AppHeader
      @toggle-playlist="handleShowPlaylist"
      @toggle-help="handleShowHelp"
      @addYtUrls="handleAddVideoIdsThroughInput"
      :activeStage="showStage"
    />

    <div :class="['appMain', showStage === stages.INTRO ? 'stretched' : '']">
      <ConfirmModal
        v-if="showPlaylistRemoveConfirmation"
        @close="onCloseClearPlaylistConfirmation"
        @confirm="onConfirmPlaylistRemove"
      >
        <p slot="body">
          Please confirm that you want to clear the complete playlist. All
          videos will be removed.
        </p>
      </ConfirmModal>

      <SharePlaylistModal
        v-if="showPlaylistShareModal"
        @close="onCloseSharePlaylistModal"
      >
        <p slot="body">
          Your playlist URL is: <a :href="playlistURL">{{ playlistURL }}</a>
        </p>
      </SharePlaylistModal>

      <notifications />
      <DropArea
        @dropMode="handleDropModeChange"
        @droppedSongs="handleDroppedSongs"
      />

      <!--
        Player wrapper is needed because YT api gets confused if it's container starts disappearing or switching places in its parent node
        This way we always maintain it's container in the DOM
      -->
      <div
        v-show="videoSlice"
        class="appPlayerWrap"
        :class="{ 'no-pointer-events': disablePlayerPointerEvents }"
      >
        <Player
          v-if="videoSlice"
          :class="{ 'no-pointer-events': dropMode }"
          ref="player"
          :videoId="videoSlice.videoId"
          :startSeconds="videoSlice.startSeconds"
          :endSeconds="videoSlice.endSeconds"
          :halfScreen="isPlaylistOpen"
          @ended="handleSongEnded"
          @playing="handleVideoPlaying"
          @ready="handlePlayerReady"
          @paused="handleVideoPaused"
          @duration="onDuration"
          @currentTime="onCurrentTime"
          @error="onPlaybackError"
        />
      </div>

      <HowTo v-show="showStage === stages.INTRO" />
      <SongList
        v-show="showStage === stages.PLAYLIST"
        :playlist="playlist"
        :playlistIndex="playlistIndex"
        @shuffle="onPlaylistShuffle"
        @clearPlaylist="onClearPlaylist"
        @selectedSongIndex="playlistSetIndex"
        @videoInfoError="onVideoInfoError"
        @playlistOrderChange="onPlaylistOrderChange"
        @generatePlaylistURL="onGeneratePlaylistURL"
      />
      <HelpScreen v-show="showStage === stages.HELP" />
    </div>

    <Controls
      v-if="videoSlice"
      @previous="playlistPrevious"
      @next="playlistNext"
      @remove="removeCurrentSong"
      @seek="onSeek"
      @play="onControlPlay"
      @pause="onControlPause"
      @setVolume="onSetVolume"
      @mute="onMute"
      @unmute="onUnmute"
      @startedMouseTracking="onVolumeStartedMouseTracking"
      @stoppedMouseTracking="onVolumeStoppedMouseTracking"
      :duration="duration"
      :currentTime="currentTime"
      :playing="playing"
      :playerVolume="playerVolume"
      :muted="muted"
    />
  </div>
</template>

<script>
import GlobalEvents from "vue-global-events";
import DropArea from "@/components/dropArea/DropArea";
import Player from "@/components/player/Player";
import Controls from "@/components/controls/Controls";
import PlaylistMixin from "@/mixins/Playlist";
import SongList from "@/components/songList/SongList";
import HowTo from "@/components/howTo/HowTo";
import HelpScreen from "@/components/howTo/HelpScreen";
import AppHeader from "@/components/appHeader/AppHeader";
import ConfirmModal from "@/components/modal/confirmModal/ConfirmModal";
import SharePlaylistModal from "@/components/modal/sharePlaylistModal/SharePlaylistModal";
import { getYtVideoId, getYtUrls } from "@/utils/string";
import "./global.css";

const stages = {
  INTRO: "intro",
  PLAYING: "playing",
  PLAYLIST: "playlist",
  HELP: "help",
};

export default {
  name: "App",

  mixins: [PlaylistMixin],

  components: {
    Player,
    Controls,
    GlobalEvents,
    DropArea,
    SongList,
    HowTo,
    HelpScreen,
    AppHeader,
    ConfirmModal,
    SharePlaylistModal,
  },

  data: function() {
    return {
      videoSlice: null,
      dropMode: false,
      duration: 0,
      currentTime: 0,
      playing: false,
      playerVolume: 0,
      muted: false,
      stages: stages,
      showStage: stages.INTRO,
      showPlaylistRemoveConfirmation: false,
      showPlaylistShareModal: false,
      playlistURL: "",
      disablePlayerPointerEvents: false,
      // manage lost focus on kbd shortcuts window switching. Not detected using visibility change event
      pageLostFocusFnReference: null,
      pageLostFocusTimeout: null,
    };
  },

  created() {
    this.handleWindowUnloadEvent();
    this.pageLostFocusFnReference = () => this.adjustToPageLostFocus();
    this.pageLostFocusFnReference();
  },

  computed: {
    isPlaylistOpen() {
      return this.showStage === stages.PLAYLIST;
    },
  },

  mounted() {
    // Load playlist for playlist ID or fallback to local storage
    const playlistId = this.$utils.string.getSearchParam(
      window.location.href,
      "p"
    );
    if (playlistId) {
      this.loadPlaylistFromPlaylistId(playlistId)
        .then((songlistObjects) => {
          this.playlistAddSongs(songlistObjects);
          this.playlistSetIndex(0);
        })
        .catch(() => {
          this.loadPlaylistFromLocalStorage();
        });
    } else {
      // try to load existing playlist info from localstorage
      this.loadPlaylistFromLocalStorage();
    }

    // keep volume value in sync
    setInterval(() => {
      if (this.$refs.player) {
        this.playerVolume = this.$refs.player.getVolume() ?? 0;
        this.muted = this.$refs.player.isMuted() ?? false;
      }
    }, 500);
  },

  methods: {
    loadPlaylistFromPlaylistId(playlistId) {
      return this.$http.fetchPlaylist(playlistId).then((response) => {
        const {videoIds} = response
        return videoIds.map(id => ({videoId: id}))
      });
    },

    loadPlaylistFromLocalStorage() {
      const { songList, index } = this.$localstorage.getPlaylist();
      const songlistObjects = songList.map((videoId) => ({ videoId }));
      this.playlistAddSongs(songlistObjects);
      this.playlistSetIndex(index);
    },

    playVideoSlice(videoSlice) {
      this.videoSlice = videoSlice;
    },

    handleWindowUnloadEvent() {
      // don't block refresh/close tab in dev environment
      // TODO: use env variables
      if (window.location.href.includes("http://localhost")) {
        return;
      }

      window.addEventListener("beforeunload", this.onBeforeUnload);
    },

    // handles a situation where we switch to another window(browser?) using kbd shortcuts
    // this situation is not detected by handling visibility change since the current tab
    // is still left opened. But when we are returning from another window, we may be dragging links
    // to drop inside of this window. In that case, player events need to be disabled like in the
    // rest of the cases
    adjustToPageLostFocus() {
      if (
        (!document.hasFocus() || document.visibilityState == "hidden") &&
        !this.disablePlayerPointerEvents
      ) {
        this.disablePlayerPointerEvents = true;
      }

      this.pageLostFocusTimeout = setTimeout(() => {
        this.adjustToPageLostFocus();
      }, 500);
    },

    onPageVisibilityChange() {
      // react to tab going out of focus: document.hidden value
      if (document.hidden) {
        this.disablePlayerPointerEvents = true;
      }
    },

    handlePageMouseLeave() {
      // mouse has left the document
      // the same thing is also handled in the handlePageMouseOut handler hack
      // for firefox/safari
      this.disablePlayerPointerEvents = true;
    },
    // firefox/safari mouseleave hack. They don't support the mouseleave event
    // mouseout is used instead, but... it fires on any child leave -_- so we
    // need to detect when the document node has been left
    // TODO: reconsider this event & try to skip this handler for Chrome
    handlePageMouseOut(e) {
      e = e ? e : window.event;
      var from = e.relatedTarget || e.toElement;
      if (!from || from.nodeName == "HTML") {
        // mouse has left the document
        this.disablePlayerPointerEvents = true;
      }
    },
    handlePageMouseEnter(e) {
      if (!this.videoSlice) return;

      const isDragEvent = e instanceof DragEvent;
      if (!isDragEvent) {
        // cancel possible pointer settings
        this.disablePlayerPointerEvents = false;
        return;
      }

      this.disablePlayerPointerEvents = true;
    },
    handlePageMouseMove(e) {
      if (!this.videoSlice) return;

      const isDragEvent = e instanceof DragEvent;
      if (!isDragEvent) {
        // cancel possible pointer settings
        this.disablePlayerPointerEvents = false;
        return;
      }

      this.disablePlayerPointerEvents = true;
    },

    handlePageDrop() {
      this.disablePlayerPointerEvents = false;
    },

    onVolumeStartedMouseTracking() {
      this.disablePlayerPointerEvents = true;
    },

    onVolumeStoppedMouseTracking() {
      this.disablePlayerPointerEvents = false;
    },

    handleDropModeChange(dropMode) {
      this.dropMode = dropMode;
    },

    handleDroppedSongs(ytUrls = []) {
      const addedCount = this.playlistAddSongs(ytUrls);
      this.$notify({
        text: `${addedCount} video URLs appended!`,
      });
    },

    handleAddVideoIdsThroughInput(videoIds = []) {
      const ytUrls = videoIds.map((vId) => ({ videoId: vId }));
      const addedCount = this.playlistAddSongs(ytUrls);
      this.$notify({
        text: `${addedCount} video URLs appended!`,
      });
    },

    handleGlobalPasteEvent(event) {
      const eventText = event?.clipboardData?.getData("text");

      if (!eventText) return;

      const ytUrls = getYtUrls(eventText);
      const videoIds = ytUrls.map(getYtVideoId);
      const ytVideos = videoIds.map((vId) => ({ videoId: vId }));
      const addedCount = this.playlistAddSongs(ytVideos);
      this.$notify({
        text: `${addedCount} video URLs appended!`,
      });
      // restore normal functionality
      this.disablePlayerPointerEvents = false;
    },

    handleUpcomingSelected(offset) {
      this.playlistSetIndex(this.playlistIndex + offset);
    },

    onVideoInfoError(videoId) {
      this.playlistRemoveSong(videoId);
    },

    onPlaybackError() {
      this.removeCurrentSong();
      // this.$notify({
      //   text: `Removed videos that can't be played`,
      //   type: "error",
      // });
    },

    removeCurrentSong() {
      this.playlistRemoveSong(this.videoSlice.videoId);
    },

    onSeek(time) {
      this.currentTime = time;
      this.$refs.player.seek(time);
    },

    onControlPlay() {
      this.$refs.player.play();
    },

    onControlPause() {
      this.$refs.player.pause();
    },

    onSetVolume(volume) {
      this.$refs.player.setVolume(volume);
      this.playerVolume = volume;
    },

    onMute() {
      this.$refs.player.mute();
      this.muted = true;
    },

    onUnmute() {
      this.$refs.player.unmute();
      this.muted = false;
    },

    onCurrentTime(time) {
      this.currentTime = time;
    },

    onDuration(duration) {
      this.duration = duration;
    },

    handleSongEnded() {
      if (this.playlistGetLength() > 1) {
        this.playlistNext();
      } else {
        // hack to loop a single song, when playlist.length === 1
        this.$refs.player.seek(0);
      }
    },

    handleVideoPlaying() {
      this.playing = true;
    },

    handlePlayerReady() {
      // setTimeout(() => {
      //   this.playerVolume = this.$refs.player.getVolume();
      // }, 250);
    },

    handleVideoPaused() {
      this.playing = false;
    },

    setCurrentVideoSlice() {
      // nothing to play
      if (!this.playlistGetLength()) {
        this.videoSlice = null;
        this.showStage = stages.INTRO;
        return;
      }

      // setting first songs for the playlist, move to playing mode
      if (this.showStage === stages.INTRO) {
        this.showStage = stages.PLAYING;
      }

      const currentSong = this.playlistGetCurrentSong();

      this.videoSlice = {
        videoId: currentSong.videoId,
        // startSeconds: currentSong.startSeconds ?? 0,
        startSeconds: 0,
      };
    },

    onBeforeUnload(e) {
      e = e || window.event;

      // For IE and Firefox prior to version 4
      if (e) {
        e.returnValue = "Sure?";
      }

      // For Safari
      return "Sure?";
    },

    handleShowPlaylist() {
      if (this.showStage !== stages.PLAYLIST) {
        this.showStage = stages.PLAYLIST;
      } else {
        if (this.playlistGetLength()) {
          this.showStage = stages.PLAYING;
        } else {
          this.showStage = stages.INTRO;
        }
      }
    },

    handleShowHelp() {
      if (this.showStage !== stages.HELP) {
        this.showStage = stages.HELP;
      } else {
        if (this.playlistGetLength()) {
          this.showStage = stages.PLAYING;
        } else {
          this.showStage = stages.INTRO;
        }
      }
    },

    handleShowPlaying() {
      if (this.playlistGetLength()) {
        this.showStage = stages.PLAYING;
      }
    },

    onPlaylistOrderChange(newPlaylist) {
      this.playlistChangeOrder(newPlaylist);
    },

    onPlaylistShuffle() {
      this.playlistShuffle();
    },

    onClearPlaylist() {
      this.showPlaylistRemoveConfirmation = true;
    },
    onCloseClearPlaylistConfirmation() {
      this.showPlaylistRemoveConfirmation = false;
    },
    onConfirmPlaylistRemove() {
      this.playlistClear();
      this.showPlaylistRemoveConfirmation = false;
    },
    onGeneratePlaylistURL() {
      const videoIds = this.playlist.map((video) => video.videoId);
      this.$http
        .createPlaylist(videoIds)
        .then((playlistId) => {
          if (playlistId) {
            this.playlistURL = `${window.location.origin}?p=${playlistId}`;
            this.showPlaylistShareModal = true;
          } else {
            throw new Error("No playlist ID");
          }
        })
        .catch(() => {
          this.$notify({
            text: `Failed to create playlist URL. Please try again.`,
            type: "error",
          });
        });
    },
    onCloseSharePlaylistModal() {
      this.playlistURL = "";
      this.showPlaylistShareModal = false;
    },
  },

  watch: {
    playlistIndex() {
      this.currentTime = 0; // preemptively set to 0
      this.setCurrentVideoSlice();
      this.$localstorage.savePlaylist(this.playlist, this.playlistIndex);
    },
    playlist() {
      this.setCurrentVideoSlice();
      this.$localstorage.savePlaylist(this.playlist, this.playlistIndex);
    },
  },
};
</script>

// apps/web/app/App.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { useParams } from '@tanstack/react-router'
import AppHeader from '~/components/AppHeader/AppHeader'
import Player, { type PlayerHandle } from '~/components/Player/Player'
import DropArea from '~/components/DropArea/DropArea'
import SongList from '~/components/SongList/SongList'
import HowTo from '~/components/HowTo/HowTo'
import HelpScreen from '~/components/HelpScreen/HelpScreen'
import Loader from '~/components/Loader/Loader'
import { useNotify } from '~/components/Notifications'
import { usePlaylist } from '~/hooks/usePlaylist'
import { getYtVideoId, getYtUrls } from '~/lib/string'
import {
  fetchPlaylist as fetchPlaylistApi,
  createPlaylist,
  updatePlaylist,
} from '~/lib/http'

interface VideoSlice {
  videoId: string
  startSeconds: number
  endSeconds?: number
}

const stages = {
  INTRO: 'intro',
  PLAYING: 'playing',
  PLAYLIST: 'playlist',
  HELP: 'help',
} as const

type Stage = (typeof stages)[keyof typeof stages]

export default function App() {
  const notify = useNotify()
  const playerRef = useRef<PlayerHandle>(null)

  // Playlist id from the /p/$playlistId route (undefined on the index route).
  // `strict: false` lets the same component serve both routes.
  const params = useParams({ strict: false }) as { playlistId?: string }
  const routePlaylistId = params.playlistId ?? null

  const {
    playlist,
    playlistIndex,
    playlistAddSongs,
    playlistRemoveSong,
    playlistSetIndex,
    playlistPrevious,
    playlistNext,
    playlistShuffle,
    playlistChangeOrder,
    playlistGetCurrentSong,
    playlistGetLength,
  } = usePlaylist()

  const [videoSlice, setVideoSlice] = useState<VideoSlice | null>(null)
  const [dropMode, setDropMode] = useState(false)
  // True while a playlist referenced by the /p/:id route is being fetched. Drives
  // a centered loader over an otherwise empty main area until the playlist is
  // loaded (or fails), so we never flash the intro screen on a shared link.
  const [isLoadingPlaylist, setIsLoadingPlaylist] = useState(
    routePlaylistId !== null,
  )
  const [showStage, setShowStage] = useState<Stage>(stages.INTRO)
  // VideoIds of the playlist as last persisted on the backend. null means no
  // backend-backed playlist exists yet for this session. Compared against the
  // current playlist to detect unsaved changes (add/remove/reorder).
  const [backendVideoIds, setBackendVideoIds] = useState<string[] | null>(null)
  // The backend id of the playlist this session is bound to, and whether this
  // browser's owner token owns it. A loaded playlist we don't own is "foreign":
  // read-only, with a "Make a copy" action instead of auto-save.
  const [playlistId, setPlaylistId] = useState<string | null>(null)
  const [isOwner, setIsOwner] = useState(false)
  const [isSavingPlaylist, setIsSavingPlaylist] = useState(false)
  // Optional playlist title + emoji, and the versions last persisted to the
  // backend (used to detect unsaved meta changes). Empty string = unset.
  const [playlistName, setPlaylistName] = useState('')
  const [playlistEmoji, setPlaylistEmoji] = useState('')
  const [backendName, setBackendName] = useState<string | null>(null)
  const [backendEmoji, setBackendEmoji] = useState<string | null>(null)
  const [disablePlayerPointerEvents, setDisablePlayerPointerEvents] =
    useState(false)

  // Refs for values used in event handlers to avoid stale closures
  const videoSliceRef = useRef(videoSlice)
  const disablePlayerPointerEventsRef = useRef(disablePlayerPointerEvents)
  const showStageRef = useRef(showStage)
  videoSliceRef.current = videoSlice
  disablePlayerPointerEventsRef.current = disablePlayerPointerEvents
  showStageRef.current = showStage

  // --- Derived state ---
  const isPlaylistOpen = showStage === stages.PLAYLIST

  // --- Set current video slice based on playlist state ---
  const setCurrentVideoSlice = useCallback(() => {
    if (!playlist.length) {
      setVideoSlice(null)
      setShowStage(stages.INTRO)
      return
    }

    setShowStage((prev) =>
      prev === stages.INTRO ? stages.PLAYING : prev,
    )

    const currentSong = playlist[playlistIndex]
    if (currentSong) {
      setVideoSlice({
        videoId: currentSong.videoId,
        startSeconds: 0,
      })
    }
  }, [playlist, playlistIndex])

  useEffect(() => {
    setCurrentVideoSlice()
  }, [playlist, playlistIndex, setCurrentVideoSlice])

  // --- Dirty tracking ---
  // The playlist is "dirty" when the local set/order of videoIds differs from
  // what's been persisted to the backend. While the initial auto-create POST is
  // in flight (backendVideoIds still null with a non-empty playlist), nothing
  // is persisted yet either — treat that as dirty so we warn on unload.
  const currentVideoIds = playlist.map((s) => s.videoId)
  const currentVideoIdsKey = currentVideoIds.join(',')
  const isPlaylistDirty =
    playlist.length > 0 &&
    (backendVideoIds === null ||
      backendVideoIds.length !== currentVideoIds.length ||
      backendVideoIds.some((id, i) => id !== currentVideoIds[i]))

  // Normalized current meta ('' → null) and whether it diverges from what's
  // persisted. Only meaningful once a backend playlist exists.
  const currentMeta = {
    name: playlistName.trim() || null,
    emoji: playlistEmoji || null,
  }
  const isMetaDirty =
    backendVideoIds !== null &&
    (currentMeta.name !== backendName || currentMeta.emoji !== backendEmoji)

  // A "foreign" playlist is one we've loaded but don't own. It's read-only;
  // editing requires making a copy first. A freshly-built playlist (no backend
  // id yet) is never foreign — we become its owner on auto-create.
  const isForeign = playlistId !== null && !isOwner
  const isForeignRef = useRef(isForeign)
  isForeignRef.current = isForeign

  // Generation counter: any in-flight POST that resolves after a clear/reset
  // should not retro-actively re-populate backendVideoIds or the URL.
  const persistGenRef = useRef(0)
  const autoCreateInFlightRef = useRef(false)
  const loadingFromUrlRef = useRef(false)

  // Reflect the bound playlist id in the URL as /p/:id without triggering a
  // router navigation (which would remount this component and reload state).
  const setPlaylistUrl = useCallback((id: string) => {
    window.history.replaceState(null, '', `/p/${id}`)
  }, [])

  // Create a backend playlist owned by this browser (token sent by the http
  // layer), bind the session to it, and reflect its id in the URL.
  const createOwnedPlaylist = useCallback(
    (
      snapshot: string[],
      meta: { name: string | null; emoji: string | null },
      gen: number,
    ) => {
      setIsSavingPlaylist(true)
      return createPlaylist(snapshot, meta)
        .then((newId: string | undefined) => {
          if (gen !== persistGenRef.current) return
          if (!newId) throw new Error('No playlist ID')
          setBackendVideoIds(snapshot)
          setBackendName(meta.name)
          setBackendEmoji(meta.emoji)
          setPlaylistId(newId)
          setIsOwner(true)
          setPlaylistUrl(newId)
        })
        .finally(() => {
          setIsSavingPlaylist(false)
        })
    },
    [setPlaylistUrl],
  )

  // Persist the current playlist (videos + order) to an owned backend playlist
  // in one request. Demotes us to non-owner if the server rejects the token.
  const saveOwnedPlaylist = useCallback(
    (
      id: string,
      snapshot: string[],
      meta: { name: string | null; emoji: string | null },
      gen: number,
    ) => {
      setIsSavingPlaylist(true)
      return updatePlaylist(id, snapshot, meta)
        .then((result) => {
          if (gen !== persistGenRef.current) return
          if (result === 'ok') {
            setBackendVideoIds(snapshot)
            setBackendName(meta.name)
            setBackendEmoji(meta.emoji)
          } else if (result === 'forbidden' || result === 'not_found') {
            setIsOwner(false)
            notify({
              text: "You can't edit this playlist. Make a copy to save your changes.",
              type: 'error',
            })
          } else {
            notify({
              text: 'Failed to save playlist changes. Retrying…',
              type: 'error',
            })
          }
        })
        .finally(() => {
          setIsSavingPlaylist(false)
        })
    },
    [notify],
  )

  // --- Mount: Load playlist from the /p/:id route param ---
  const mountedRef = useRef(false)
  useEffect(() => {
    if (mountedRef.current) return
    mountedRef.current = true

    const urlPlaylistId = routePlaylistId
    if (!urlPlaylistId) return

    loadingFromUrlRef.current = true
    const gen = persistGenRef.current
    fetchPlaylistApi(urlPlaylistId)
      .then((response) => {
        if (gen !== persistGenRef.current) return
        if (!response) return
        const songlistObjects = response.videoIds.map((vid: string) => ({
          videoId: vid,
        }))
        playlistAddSongs(songlistObjects)
        playlistSetIndex(0)
        setBackendVideoIds(response.videoIds)
        setPlaylistId(response.id)
        setIsOwner(response.isOwner)
        setPlaylistName(response.name ?? '')
        setPlaylistEmoji(response.emoji ?? '')
        setBackendName(response.name ?? null)
        setBackendEmoji(response.emoji ?? null)
      })
      .finally(() => {
        loadingFromUrlRef.current = false
        setIsLoadingPlaylist(false)
      })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // --- Auto-create a backend playlist as soon as a video is added ---
  // Fires once when the local playlist first becomes non-empty without a
  // backend-backed playlist. We become its owner; subsequent edits are then
  // debounced and auto-saved against it.
  useEffect(() => {
    if (playlist.length === 0) return
    if (backendVideoIds !== null) return
    if (loadingFromUrlRef.current) return
    if (autoCreateInFlightRef.current) return

    autoCreateInFlightRef.current = true
    const snapshot = playlist.map((s) => s.videoId)
    const gen = persistGenRef.current
    createOwnedPlaylist(
      snapshot,
      { name: playlistName.trim() || null, emoji: playlistEmoji || null },
      gen,
    )
      .catch(() => {
        notify({
          text: 'Failed to create a shareable playlist. You can try again with Save.',
          type: 'error',
        })
      })
      .finally(() => {
        autoCreateInFlightRef.current = false
      })
  }, [
    playlist,
    backendVideoIds,
    notify,
    createOwnedPlaylist,
    playlistName,
    playlistEmoji,
  ])

  // --- Auto-save owned playlists ---
  // Once we own a backend playlist, every edit (add/remove/reorder/shuffle) is
  // debounced and persisted in a single PUT. The effect reschedules whenever the
  // videoIds change or a save settles, so edits made during an in-flight save
  // are coalesced into a follow-up save.
  useEffect(() => {
    if (!isOwner || !playlistId) return
    if (!isPlaylistDirty && !isMetaDirty) return
    if (isSavingPlaylist) return

    const snapshot = currentVideoIdsKey ? currentVideoIdsKey.split(',') : []
    const meta = {
      name: playlistName.trim() || null,
      emoji: playlistEmoji || null,
    }
    const gen = persistGenRef.current
    const handle = setTimeout(() => {
      saveOwnedPlaylist(playlistId, snapshot, meta, gen)
    }, 800)
    return () => clearTimeout(handle)
  }, [
    isOwner,
    playlistId,
    isPlaylistDirty,
    isMetaDirty,
    isSavingPlaylist,
    currentVideoIdsKey,
    playlistName,
    playlistEmoji,
    saveOwnedPlaylist,
  ])

  // --- Before unload warning ---
  // Warn whenever local state has unsaved changes against the backend.
  useEffect(() => {
    // Foreign playlists are read-only and never persisted, so don't warn on them.
    if ((!isPlaylistDirty && !isMetaDirty) || isForeign) return

    const onBeforeUnload = (e: BeforeUnloadEvent) => {
      e.preventDefault()
      e.returnValue = 'Sure?'
      return 'Sure?'
    }

    window.addEventListener('beforeunload', onBeforeUnload)
    return () => window.removeEventListener('beforeunload', onBeforeUnload)
  }, [isPlaylistDirty, isMetaDirty, isForeign])

  // --- Document title reflects the playlist's emoji + title ---
  // Format: "<emoji> <title> - y2pilot", with each part optional (just
  // "y2pilot" when neither is set).
  useEffect(() => {
    const prefix = [playlistEmoji.trim(), playlistName.trim()]
      .filter(Boolean)
      .join(' ')
    // Keep the landing page's SEO title until a playlist exists.
    if (!prefix && !playlistId && !routePlaylistId) return
    document.title = prefix ? `${prefix} - y2pilot` : 'y2pilot'
  }, [playlistEmoji, playlistName, playlistId, routePlaylistId])

  // --- Page focus / visibility management ---
  useEffect(() => {
    const onVisibilityChange = () => {
      if (document.hidden) {
        setDisablePlayerPointerEvents(true)
      }
    }
    document.addEventListener('visibilitychange', onVisibilityChange)
    return () =>
      document.removeEventListener('visibilitychange', onVisibilityChange)
  }, [])

  // Polling for lost focus (handles window switching via kbd shortcuts)
  useEffect(() => {
    const interval = setInterval(() => {
      if (!document.hasFocus() || document.visibilityState === 'hidden') {
        setDisablePlayerPointerEvents(true)
      }
    }, 500)
    return () => clearInterval(interval)
  }, [])

  // --- Global drag/drop prevention and mouse events ---
  useEffect(() => {
    const prevent = (e: Event) => e.preventDefault()
    document.addEventListener('dragenter', prevent)
    document.addEventListener('dragover', prevent)

    const onDrop = () => setDisablePlayerPointerEvents(false)

    const onMouseLeave = () => setDisablePlayerPointerEvents(true)

    const onMouseOut = (e: MouseEvent) => {
      const from = e.relatedTarget as Node | null
      if (!from || (from as Element).nodeName === 'HTML') {
        setDisablePlayerPointerEvents(true)
      }
    }

    const onMouseEnter = (e: MouseEvent) => {
      if (!videoSliceRef.current) return
      if (e instanceof DragEvent) {
        setDisablePlayerPointerEvents(true)
      } else {
        setDisablePlayerPointerEvents(false)
      }
    }

    const onMouseMove = (e: MouseEvent) => {
      if (!videoSliceRef.current) return
      if (e instanceof DragEvent) {
        setDisablePlayerPointerEvents(true)
      } else {
        setDisablePlayerPointerEvents(false)
      }
    }

    document.addEventListener('drop', onDrop)
    document.addEventListener('mouseleave', onMouseLeave)
    document.addEventListener('mouseout', onMouseOut)
    document.addEventListener('mouseenter', onMouseEnter)
    document.addEventListener('mousemove', onMouseMove)

    return () => {
      document.removeEventListener('dragenter', prevent)
      document.removeEventListener('dragover', prevent)
      document.removeEventListener('drop', onDrop)
      document.removeEventListener('mouseleave', onMouseLeave)
      document.removeEventListener('mouseout', onMouseOut)
      document.removeEventListener('mouseenter', onMouseEnter)
      document.removeEventListener('mousemove', onMouseMove)
    }
  }, [])

  // --- Global paste handler ---
  useEffect(() => {
    const onPaste = (e: ClipboardEvent) => {
      // Don't handle paste from input elements
      if (
        e.target instanceof HTMLInputElement ||
        e.target instanceof HTMLTextAreaElement
      ) {
        return
      }

      if (isForeignRef.current) {
        notify({
          text: 'This playlist is read-only. Make a copy to edit it.',
          type: 'error',
        })
        return
      }

      const eventText = e.clipboardData?.getData('text')
      if (!eventText) return

      const ytUrls = getYtUrls(eventText)
      const videoIds = ytUrls.map(getYtVideoId)
      const ytVideos = videoIds
        .filter(Boolean)
        .map((vId) => ({ videoId: vId as string }))
      const addedCount = playlistAddSongs(ytVideos)
      notify({ text: `${addedCount} video URLs appended!` })
      setDisablePlayerPointerEvents(false)
    }

    document.addEventListener('paste', onPaste)
    return () => document.removeEventListener('paste', onPaste)
  }, [playlistAddSongs, notify])

  // --- Keyboard shortcuts ---
  useEffect(() => {
    const onKeyUp = (e: KeyboardEvent) => {
      if (
        e.target instanceof HTMLInputElement ||
        e.target instanceof HTMLTextAreaElement
      ) {
        return
      }

      if (e.key === '?') {
        handleShowHelp()
        return
      }
      if (e.key === 'Escape') {
        handleShowPlaying()
        return
      }

      // Playlist-related shortcuts: only active once there's a playlist.
      if (showStageRef.current === stages.INTRO) return

      if (e.shiftKey && (e.key === 'p' || e.key === 'P')) {
        handleShowPlaylist()
        return
      }
      if (e.shiftKey && (e.key === 'S' || e.key === 's')) {
        if (!isForeignRef.current) playlistShuffle()
        return
      }
      if (e.shiftKey && e.key === 'ArrowLeft') {
        playlistPrevious()
        return
      }
      if (e.shiftKey && e.key === 'ArrowRight') {
        playlistNext()
        return
      }
      if (e.shiftKey && e.code === 'Digit1') {
        handleUpcomingSelected(1)
        return
      }
      if (e.shiftKey && e.code === 'Digit2') {
        handleUpcomingSelected(2)
        return
      }
      if (e.shiftKey && e.code === 'Digit3') {
        handleUpcomingSelected(3)
        return
      }
    }

    document.addEventListener('keyup', onKeyUp)
    return () => document.removeEventListener('keyup', onKeyUp)
  })

  // --- Event handlers ---

  function handleDropModeChange(mode: boolean) {
    setDropMode(mode)
  }

  function notifyReadOnly() {
    notify({
      text: 'This playlist is read-only. Make a copy to edit it.',
      type: 'error',
    })
  }

  function handleDroppedSongs(ytUrls: Array<{ videoId: string }> = []) {
    if (isForeign) return notifyReadOnly()
    const addedCount = playlistAddSongs(ytUrls)
    notify({ text: `${addedCount} video URLs appended!` })
  }

  function handleAddVideoIdsThroughInput(videoIds: string[] = []) {
    if (isForeign) return notifyReadOnly()
    const ytUrls = videoIds.map((vId) => ({ videoId: vId }))
    const addedCount = playlistAddSongs(ytUrls)
    notify({ text: `${addedCount} video URLs appended!` })
  }

  function handleUpcomingSelected(offset: number) {
    playlistSetIndex(playlistIndex + offset)
  }

  function onVideoInfoError(videoId: string) {
    playlistRemoveSong(videoId)
  }

  function onPlaybackError() {
    if (videoSlice) {
      playlistRemoveSong(videoSlice.videoId)
    }
  }

  function handleSongEnded() {
    if (playlist.length > 1) {
      playlistNext()
    } else {
      // loop a single song
      playerRef.current?.seek(0)
    }
  }

  function handleShowPlaylist() {
    if (showStageRef.current !== stages.PLAYLIST) {
      setShowStage(stages.PLAYLIST)
    } else {
      setShowStage(playlist.length ? stages.PLAYING : stages.INTRO)
    }
  }

  function handleShowHelp() {
    if (showStageRef.current !== stages.HELP) {
      setShowStage(stages.HELP)
    } else {
      setShowStage(playlist.length ? stages.PLAYING : stages.INTRO)
    }
  }

  function handleShowPlaying() {
    setShowStage(playlist.length ? stages.PLAYING : stages.INTRO)
  }

  function onPlaylistOrderChange(newPlaylist: Array<{ videoId: string }>) {
    if (isForeign) return
    playlistChangeOrder(newPlaylist)
  }

  function onPlaylistShuffle() {
    if (isForeign) return
    playlistShuffle()
  }

  function onChangeName(newName: string) {
    if (isForeign) return
    setPlaylistName(newName)
  }

  function onChangeEmoji(newEmoji: string) {
    if (isForeign) return
    setPlaylistEmoji(newEmoji)
  }

  // Fork the current playlist into a fresh one we own. The behaviour differs by
  // ownership: viewers of a foreign (read-only) playlist take over the current
  // session with their editable copy, while owners branch off a brand-new
  // version that opens in its own tab — leaving the current playlist untouched.
  function onCopyPlaylist() {
    if (!playlist.length || isSavingPlaylist) return
    const snapshot = playlist.map((v) => v.videoId)
    const meta = {
      name: playlistName.trim() || null,
      emoji: playlistEmoji || null,
    }

    if (!isForeign) {
      // Open the tab synchronously (within the click handler) so the browser
      // doesn't treat it as a blocked popup, then point it at the new playlist
      // once the backend assigns an id. Same-origin tabs share our owner token,
      // so the new tab loads the version as editable.
      const newTab = window.open('about:blank', '_blank')
      setIsSavingPlaylist(true)
      createPlaylist(snapshot, meta)
        .then((newId) => {
          if (!newId) throw new Error('No playlist ID')
          if (newTab) newTab.location.href = `/p/${newId}`
          notify({ text: 'New version created in a new tab.' })
        })
        .catch(() => {
          if (newTab) newTab.close()
          notify({
            text: 'Failed to create a new version. Please try again.',
            type: 'error',
          })
        })
        .finally(() => {
          setIsSavingPlaylist(false)
        })
      return
    }

    persistGenRef.current += 1
    const gen = persistGenRef.current
    createOwnedPlaylist(snapshot, meta, gen)
      .then(() => {
        if (gen !== persistGenRef.current) return
        notify({ text: "Copied! It's now your editable playlist." })
      })
      .catch(() => {
        notify({
          text: 'Failed to copy playlist. Please try again.',
          type: 'error',
        })
      })
  }

  return (
    <div className="appContainer">
      <AppHeader
        onToggleHelp={handleShowHelp}
        onTogglePlaylist={handleShowPlaylist}
        onCopyPlaylist={onCopyPlaylist}
        activeStage={showStage}
        playlistCount={playlist.length}
        playlistName={playlistName}
        isOwner={!isForeign}
        isSavingPlaylist={isSavingPlaylist}
      />

      <div className="appMain">
        <DropArea
          onDropMode={handleDropModeChange}
          onDroppedSongs={handleDroppedSongs}
        />

        {/*
          Player wrapper is needed because YT API gets confused if its container
          starts disappearing or switching places in its parent node.
          This way we always maintain its container in the DOM.
        */}
        <div
          style={{ display: videoSlice ? undefined : 'none' }}
          className={`appPlayerWrap ${disablePlayerPointerEvents ? 'no-pointer-events' : ''}`}
        >
          {videoSlice && (
            <Player
              className={dropMode ? 'no-pointer-events' : ''}
              ref={playerRef}
              videoId={videoSlice.videoId}
              startSeconds={videoSlice.startSeconds}
              endSeconds={videoSlice.endSeconds}
              halfScreen={isPlaylistOpen}
              onEnded={handleSongEnded}
              onReady={() => {}}
              onError={onPlaybackError}
            />
          )}
        </div>

        <div
          style={{
            display:
              showStage === stages.INTRO && !isLoadingPlaylist
                ? undefined
                : 'none',
            height: '100%',
          }}
        >
          <HowTo onAddYtUrls={handleAddVideoIdsThroughInput} />
        </div>
        <div
          style={{
            display: showStage === stages.PLAYLIST ? undefined : 'none',
          }}
        >
          <SongList
            playlist={playlist}
            playlistIndex={playlistIndex}
            onShuffle={onPlaylistShuffle}
            onSelectedSongIndex={(i) => playlistSetIndex(i)}
            onVideoInfoError={onVideoInfoError}
            onPlaylistOrderChange={onPlaylistOrderChange}
            onPrevious={playlistPrevious}
            onNext={playlistNext}
            onRemoveSong={playlistRemoveSong}
            onAddYtUrls={handleAddVideoIdsThroughInput}
            notify={notify}
            readOnly={isForeign}
            name={playlistName}
            emoji={playlistEmoji}
            onChangeName={onChangeName}
            onChangeEmoji={onChangeEmoji}
          />
        </div>
        {/* Mounted only when open so the prerendered index doesn't duplicate /help. */}
        {showStage === stages.HELP && <HelpScreen />}

        {isLoadingPlaylist && <Loader />}
      </div>

    </div>
  )
}
