// apps/web/app/components/SongList/SongList.tsx
import { useState, useEffect, useCallback, useRef } from 'react'
import {
  DragDropContext,
  Droppable,
  Draggable,
  type DropResult,
} from '@hello-pangea/dnd'
import { Shuffle, Trash2, GripVertical } from 'lucide-react'
import { textElipsis } from '~/lib/string'
import { fetchOembedBatch } from '~/lib/http'
import type { Song } from '~/hooks/usePlaylist'
import css from './SongList.module.css'

interface SongInfo {
  videoId: string
  title: string
  thumbUrl: string
  [key: string]: unknown
}

interface SongListProps {
  playlist: Song[]
  playlistIndex: number
  onShuffle: () => void
  onClearPlaylist: () => void
  onSelectedSongIndex: (index: number) => void
  onVideoInfoError: (videoId: string) => void
  onPlaylistOrderChange: (newPlaylist: Song[]) => void
  onGeneratePlaylistURL: () => void
  notify: (opts: { text: string; type?: string; duration?: number }) => void
}

const stopProp = (e: React.DragEvent) => e.stopPropagation()

export default function SongList({
  playlist,
  playlistIndex,
  onShuffle,
  onClearPlaylist,
  onSelectedSongIndex,
  onVideoInfoError,
  onPlaylistOrderChange,
  onGeneratePlaylistURL,
  notify,
}: SongListProps) {
  const [songInfo, setSongInfo] = useState<Record<string, SongInfo>>({})
  const [loading, setLoading] = useState(false)
  const [playlistCopy, setPlaylistCopy] = useState<Song[]>([])
  const prevPlaylistRef = useRef<Song[]>([])

  useEffect(() => {
    // Only update when playlist actually changes
    if (prevPlaylistRef.current !== playlist) {
      prevPlaylistRef.current = playlist
      setPlaylistCopy([...playlist])
    }
  }, [playlist])

  // Fetch song info when playlistCopy changes
  useEffect(() => {
    if (!playlistCopy.length) return

    const videoIds = playlistCopy.map((v) => v.videoId)

    // Skip if we already have info for all videos
    const missingIds = videoIds.filter((id) => !songInfo[id])
    if (missingIds.length === 0) return

    setLoading(true)
    fetchOembedBatch(videoIds)
      .then((response) => {
        const videos = response.videos || []
        const failedVideos = (response.failed || []) as Array<{ videoId: string }>

        failedVideos.forEach((fail) => {
          onVideoInfoError(fail.videoId)
        })

        if (failedVideos.length) {
          notify({
            text: "Unfortunately, some videos couldn't load. It may be because of geographic restrictions, video settings or the video doesn't exist anymore. Please try to use another link.",
            type: 'error',
            duration: 12000,
          })
        }

        setSongInfo((prev) => {
          const next = { ...prev }
          videos.forEach(
            (oembed: { videoId: string; video: SongInfo } | undefined) => {
              if (oembed) {
                next[oembed.videoId] = oembed.video
              }
            },
          )
          return next
        })
      })
      .finally(() => {
        setLoading(false)
      })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [playlistCopy])

  const songNumber = playlistCopy.length

  const createTextElipsisDisplay = useCallback(
    (text: string) => textElipsis(text, 60),
    [],
  )

  const songThumbStyle = useCallback(
    (info: SongInfo) => ({
      backgroundImage: `url(${info.thumbUrl})`,
    }),
    [],
  )

  const handleDragEnd = useCallback(
    (result: DropResult) => {
      if (!result.destination) return

      const items = Array.from(playlistCopy)
      const [moved] = items.splice(result.source.index, 1)
      items.splice(result.destination.index, 0, moved)
      setPlaylistCopy(items)
      onPlaylistOrderChange(items)
    },
    [playlistCopy, onPlaylistOrderChange],
  )

  return (
    <div
      className={css.editor}
      onDrag={stopProp}
      onDragStart={stopProp}
      onDragEnd={stopProp}
      onDragOver={stopProp}
      onDrop={stopProp}
      onDragEnter={stopProp}
      onDragLeave={stopProp}
    >
      <header className={css.header}>
        <h3>
          {loading ? (
            <span>loading videos...</span>
          ) : (
            <span>Playlist &ndash; {songNumber} videos</span>
          )}
        </h3>
        {songNumber > 0 && (
          <div className={css.playlistControls}>
            <button onClick={onShuffle}>
              <Shuffle size={26} />
            </button>
            <button onClick={onClearPlaylist}>
              <Trash2 size={26} />
            </button>
            <button className={css.textButton} onClick={onGeneratePlaylistURL}>
              Create Playlist URL to share
            </button>
          </div>
        )}
      </header>

      {playlistCopy.length > 0 && (
        <DragDropContext onDragEnd={handleDragEnd}>
          <Droppable droppableId="playlist">
            {(provided) => (
              <ul
                className="list-group"
                ref={provided.innerRef}
                {...provided.droppableProps}
              >
                {playlistCopy.map((song, i) => (
                  <Draggable
                    key={song.videoId}
                    draggableId={song.videoId}
                    index={i}
                  >
                    {(dragProvided) => (
                      <li
                        ref={dragProvided.innerRef}
                        {...dragProvided.draggableProps}
                        className={`${css.songUrl} ${i === playlistIndex ? css.activeSongUrl : ''}`}
                        onClick={() => onSelectedSongIndex(i)}
                      >
                        <span
                          className={css.dragHandle}
                          {...dragProvided.dragHandleProps}
                        >
                          <GripVertical
                            className={css.dragHandleIcon}
                            size={26}
                          />
                          <span className={css.dragHandleIndex}>{i + 1}</span>
                        </span>
                        {songInfo[song.videoId] && (
                          <span
                            className={css.songThumb}
                            style={songThumbStyle(songInfo[song.videoId])}
                          />
                        )}
                        <span className={css.songTitle}>
                          {songInfo[song.videoId]
                            ? createTextElipsisDisplay(
                                songInfo[song.videoId].title,
                              )
                            : song.videoId}
                        </span>
                      </li>
                    )}
                  </Draggable>
                ))}
                {provided.placeholder}
              </ul>
            )}
          </Droppable>
        </DragDropContext>
      )}
    </div>
  )
}

// src/components/songList/SongList.vue
<template>
  <div
    :class="css.editor"
    @drag.stop
    @dragstart.stop
    @dragend.stop
    @dragexit.stop
    @dragover.stop
    @drop.stop
    @dragenter.stop
    @dragleave.stop
  >
    <header :class="css.header">
      <h3>
        <span v-if="!loading">Playlist – {{ songNumber }} videos</span>
        <span v-else>loading videos...</span>
      </h3>
      <div v-if="songNumber" :class="css.playlistControls">
        <button @click="$emit('shuffle')">
          <unicon width="26" height="26" name="shuffle" fill="#4a635d" />
        </button>
        <button @click="$emit('clearPlaylist')">
          <unicon width="26" height="26" name="trash" fill="#4a635d" />
        </button>

        <button :class="css.textButton" @click="$emit('generatePlaylistURL')">
          Create Playlist URL to share
        </button>
      </div>
    </header>

    <div v-if="playlistCopy && playlistCopy.length">
      <draggable
        tag="ul"
        class="list-group"
        :animation="150"
        :handle="`.${css.dragHandle}`"
        :list="playlistCopy"
        :ghost-class="css.songUrlGhost"
        @update="onUpdate"
      >
        <li
          v-for="(song, i) in playlistCopy"
          :key="song.videoId"
          :class="[css.songUrl, { [css.activeSongUrl]: i === playlistIndex }]"
          @click="$emit('selectedSongIndex', i)"
        >
          <span :class="css.dragHandle">
            <unicon :class="css.dragHandleIcon" name="draggabledots" />
            <span :class="css.dragHandleIndex">{{ i + 1 }}</span>
          </span>
          <span
            v-if="songInfo[song.videoId]"
            :class="css.songThumb"
            :style="songThumbStyle(songInfo[song.videoId])"
          />
          <span v-if="songInfo[song.videoId]" :class="css.songTitle">
            {{ createTextElipsis(songInfo[song.videoId].title) }}
          </span>
          <span v-else :class="css.songTitle">{{ song.videoId }}</span>
        </li>
      </draggable>
    </div>
  </div>
</template>

<script>
import draggable from "vuedraggable";
import css from "./SongList.module.css";

export default {
  props: {
    playlist: {
      type: Array,
      validator: (list) =>
        list.reduce((isPlaylist, song) => {
          if (!isPlaylist) return isPlaylist;

          return !!song.videoId;
        }, true),
    },

    playlistIndex: {
      type: Number,
    },
  },

  components: {
    draggable,
  },

  data() {
    return {
      css,
      songInfo: {},
      loading: false,
      playlistCopy: [],
    };
  },

  computed: {
    songNumber() {
      return this.playlistCopy.length;
    },
  },

  methods: {
    async fetchSongInfo() {
      if (!this.playlistCopy.length) return;

      this.loading = true;
      const videoIds = this.playlistCopy.map((video) => video.videoId);

      this.$http
        .fetchOembedBatch(videoIds)
        .then((response) => {
          const videos = response.videos || [];
          const failedVideos = response.failed || [];

          failedVideos.forEach((fail) => {
            this.$emit("videoInfoError", fail.videoId);
          });

          if (failedVideos.length) {
            this.$notify({
              text: `Unfortunately, some videos couldn't load. It may be because of geographic restrictions, video settings or the video doesn't exist anymore. Please try to use another link.`,
              type: "error",
              duration: 12000,
            });
          }

          videos.forEach((oembed) => {
            this.$set(this.songInfo, oembed.videoId, oembed.video);
          });
        })
        .finally(() => {
          this.loading = false;
        });
    },

    createTextElipsis(text) {
      return this.$utils.string.textElipsis(text, 60);
    },

    songThumbStyle(songInfo) {
      return {
        backgroundImage: `url(${songInfo.thumbUrl})`,
      };
    },

    onUpdate(evt) {
      evt; // skip compiler error for unused var
      // console.log(evt);
      this.$emit("playlistOrderChange", this.playlistCopy);
    },
  },

  watch: {
    playlist() {
      this.playlistCopy = [...this.playlist];
      this.fetchSongInfo();
    },
  },
};
</script>
