// apps/web/app/components/Controls/Controls.tsx
import { useState } from 'react'
import {
  SkipBack,
  SkipForward,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Trash2,
} from 'lucide-react'
import ProgressBar from '~/components/ProgressBar/ProgressBar'
import VolumeControl from '~/components/VolumeControl/VolumeControl'
import css from './Controls.module.css'

interface ControlsProps {
  duration: number
  currentTime: number
  playing: boolean
  playerVolume: number
  muted: boolean
  onPrevious: () => void
  onNext: () => void
  onRemove: () => void
  onSeek: (time: number) => void
  onPlay: () => void
  onPause: () => void
  onSetVolume: (volume: number) => void
  onMute: () => void
  onUnmute: () => void
  onStartedMouseTracking: () => void
  onStoppedMouseTracking: () => void
}

export default function Controls({
  duration,
  currentTime,
  playing,
  playerVolume,
  muted,
  onPrevious,
  onNext,
  onRemove,
  onSeek,
  onPlay,
  onPause,
  onSetVolume,
  onMute,
  onUnmute,
  onStartedMouseTracking,
  onStoppedMouseTracking,
}: ControlsProps) {
  const [isVolumeMouseTracking, setIsVolumeMouseTracking] = useState(false)

  function handleStartedMouseTracking() {
    setIsVolumeMouseTracking(true)
    onStartedMouseTracking()
  }

  function handleStoppedMouseTracking() {
    setIsVolumeMouseTracking(false)
    onStoppedMouseTracking()
  }

  return (
    <div
      className={`${css.controls} ${isVolumeMouseTracking ? 'no-pointer-events' : ''}`}
    >
      <div className={css.fastNav}>
        <ProgressBar
          duration={duration}
          currentTime={currentTime}
          onSeek={onSeek}
        />
      </div>

      <div className={css.mainControlButtons}>
        <div className={css.firstControlSection}>
          <button onClick={onPrevious}>
            <SkipBack size={35} />
          </button>
          <button onClick={onNext}>
            <SkipForward size={35} />
          </button>

          {playing ? (
            <button onClick={onPause}>
              <Pause size={35} />
            </button>
          ) : (
            <button onClick={onPlay}>
              <Play size={35} />
            </button>
          )}

          {muted ? (
            <button onClick={onUnmute}>
              <VolumeX size={35} />
            </button>
          ) : (
            <button onClick={onMute}>
              <Volume2 size={35} />
            </button>
          )}

          <VolumeControl
            onSetVolume={onSetVolume}
            onStartedMouseTracking={handleStartedMouseTracking}
            onStoppedMouseTracking={handleStoppedMouseTracking}
            playerVolume={playerVolume}
          />
        </div>

        <div className={css.playlistControlSection}>
          <button onClick={onRemove}>
            <Trash2 size={35} />
          </button>
        </div>
      </div>
    </div>
  )
}

// src/components/controls/Controls.vue
<template>
  <div
    :class="[css.controls, isVolumeMouseTracking ? 'no-pointer-events' : '']"
  >
    <div :class="css.fastNav">
      <ProgressBar
        :duration="duration"
        :currentTime="currentTime"
        @seek="reemitSeek"
      />
    </div>

    <div :class="css.mainControlButtons">
      <div :class="css.firstControlSection">
        <button @click="$emit('previous')">
          <unicon width="35" height="35" name="step-backward" fill="#4a635d" />
        </button>
        <button @click="$emit('next')">
          <unicon width="35" height="35" name="skip-forward" fill="#4a635d" />
        </button>

        <button v-if="playing" @click="$emit('pause')">
          <unicon width="35" height="35" name="pause" fill="#4a635d" />
        </button>
        <button v-else @click="$emit('play')">
          <unicon width="35" height="35" name="play" fill="#4a635d" />
        </button>

        <button v-if="muted" @click="$emit('unmute')">
          <unicon
            width="35"
            height="35"
            name="music-tune-slash"
            fill="#4a635d"
          />
        </button>
        <button v-else @click="$emit('mute')">
          <unicon width="35" height="35" name="music" fill="#4a635d" />
        </button>

        <VolumeControl
          @setVolume="onSetVolume"
          @startedMouseTracking="onVolumeStartedMouseTracking"
          @stoppedMouseTracking="onVolumeStoppedMouseTracking"
          :playerVolume="playerVolume"
        />
      </div>

      <div :class="css.playlistControlSection">
        <button @click="$emit('remove')">
          <unicon width="35" height="35" name="trash" fill="#4a635d" />
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import ProgressBar from "./progressBar/ProgressBar";
import VolumeControl from "./volumeControl/VolumeControl";
import css from "./Controls.module.css";

export default {
  props: {
    duration: {
      type: Number,
      default: 0,
    },
    currentTime: {
      type: Number,
      default: 0,
    },
    playing: {
      type: Boolean,
      required: true,
    },
    playerVolume: {
      type: Number,
      default: 0,
    },
    muted: {
      type: Boolean,
      required: true,
    },
  },

  data() {
    return {
      css,
      isVolumeMouseTracking: false,
    };
  },

  components: { ProgressBar, VolumeControl },

  methods: {
    reemitSeek(time) {
      this.$emit("seek", time);
    },

    onSetVolume(event) {
      this.$emit("setVolume", event);
    },

    onVolumeStartedMouseTracking() {
      this.isVolumeMouseTracking = true;
      this.$emit("startedMouseTracking");
    },

    onVolumeStoppedMouseTracking() {
      this.isVolumeMouseTracking = false;
      this.$emit("stoppedMouseTracking");
    },
  },
};
</script>
