// apps/web/app/components/Player/Player.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
} from 'react'
import css from './Player.module.css'

const PLAYER_ELEMENT_ID = 'yt-player'
const PLAYER_STATE = {
  UNSTARTED: -1,
  ENDED: 0,
  PLAYING: 1,
  PAUSED: 2,
  BUFFERING: 3,
  VIDEO_CUED: 5,
}

export interface PlayerHandle {
  play(): void
  pause(): void
  seek(seconds: number, allowSeekAhead?: boolean): void
  mute(): void
  unmute(): void
  isMuted(): boolean
  setVolume(volume: number): void
  getVolume(): number
}

interface PlayerProps {
  videoId: string
  startSeconds?: number
  endSeconds?: number
  halfScreen?: boolean
  className?: string
  onEnded?: () => void
  onPlaying?: () => void
  onReady?: () => void
  onPaused?: () => void
  onDuration?: (duration: number) => void
  onCurrentTime?: (time: number) => void
  onError?: (videoId: string) => void
}

function playSlice(
  player: YT.Player,
  videoId: string,
  startSeconds?: number,
  endSeconds?: number,
) {
  const apiOptions: { videoId: string; startSeconds?: number; endSeconds?: number } = {
    videoId,
    startSeconds: startSeconds ?? 0,
  }
  if (endSeconds) {
    apiOptions.endSeconds = endSeconds
  }
  player.loadVideoById(apiOptions)
}

const Player = forwardRef<PlayerHandle, PlayerProps>(function Player(
  {
    videoId,
    startSeconds = 0,
    endSeconds,
    halfScreen = false,
    className,
    onEnded,
    onPlaying,
    onReady,
    onPaused,
    onDuration,
    onCurrentTime,
    onError,
  },
  ref,
) {
  const playerRef = useRef<YT.Player | null>(null)
  const progressIntervalRef = useRef<ReturnType<typeof setInterval>>(undefined)
  const initializedRef = useRef(false)
  const sdkIntervalRef = useRef<ReturnType<typeof setInterval>>(undefined)

  // Keep callback refs to avoid stale closures in YT event handlers
  const onEndedRef = useRef(onEnded)
  const onPlayingRef = useRef(onPlaying)
  const onReadyRef = useRef(onReady)
  const onPausedRef = useRef(onPaused)
  const onDurationRef = useRef(onDuration)
  const onCurrentTimeRef = useRef(onCurrentTime)
  const onErrorRef = useRef(onError)
  const videoIdRef = useRef(videoId)
  const startSecondsRef = useRef(startSeconds)
  const endSecondsRef = useRef(endSeconds)

  onEndedRef.current = onEnded
  onPlayingRef.current = onPlaying
  onReadyRef.current = onReady
  onPausedRef.current = onPaused
  onDurationRef.current = onDuration
  onCurrentTimeRef.current = onCurrentTime
  onErrorRef.current = onError
  videoIdRef.current = videoId
  startSecondsRef.current = startSeconds
  endSecondsRef.current = endSeconds

  useImperativeHandle(ref, () => ({
    play() {
      playerRef.current?.playVideo()
    },
    pause() {
      playerRef.current?.pauseVideo()
    },
    seek(seconds: number, allowSeekAhead = true) {
      playerRef.current?.seekTo(seconds, allowSeekAhead)
    },
    mute() {
      playerRef.current?.mute()
    },
    unmute() {
      playerRef.current?.unMute()
    },
    isMuted() {
      return playerRef.current?.isMuted?.() ?? false
    },
    setVolume(volume: number) {
      playerRef.current?.setVolume(volume)
    },
    getVolume() {
      return playerRef.current?.getVolume?.() ?? 0
    },
  }))

  // Start progress reporting
  const startProgress = () => {
    if (progressIntervalRef.current) clearInterval(progressIntervalRef.current)
    progressIntervalRef.current = setInterval(() => {
      if (playerRef.current) {
        onDurationRef.current?.(playerRef.current.getDuration?.() ?? 0)
        onCurrentTimeRef.current?.(playerRef.current.getCurrentTime?.() ?? 0)
      }
    }, 500)
  }

  // Load SDK and initialize player (once)
  useEffect(() => {
    // Load the YT IFrame API script
    if (!document.querySelector('script[src*="youtube.com/iframe_api"]')) {
      const tag = document.createElement('script')
      const firstScriptTag = document.getElementsByTagName('script')[0]
      tag.src = 'https://www.youtube.com/iframe_api'
      firstScriptTag.parentNode!.insertBefore(tag, firstScriptTag)
    }

    // Poll for SDK readiness
    sdkIntervalRef.current = setInterval(() => {
      if (window.YT && window.YT.Player && !initializedRef.current) {
        initializedRef.current = true
        clearInterval(sdkIntervalRef.current)

        const player = new window.YT.Player(PLAYER_ELEMENT_ID, {
          events: {
            onReady: () => {
              playSlice(
                player,
                videoIdRef.current,
                startSecondsRef.current,
                endSecondsRef.current,
              )
              player.seekTo(startSecondsRef.current ?? 0, true)
              startProgress()
              onReadyRef.current?.()
            },
            onError: (event) => {
              onErrorRef.current?.(videoIdRef.current)
              console.error(videoIdRef.current, event)
            },
            onStateChange: (event) => {
              switch (event.data) {
                case PLAYER_STATE.ENDED:
                  onEndedRef.current?.()
                  break
                case PLAYER_STATE.PLAYING:
                  onPlayingRef.current?.()
                  break
                case PLAYER_STATE.PAUSED:
                  onPausedRef.current?.()
                  break
              }
            },
            onPlaybackQualityChange: () => {},
            onPlaybackRateChange: () => {},
            onApiChange: () => {},
          },
        })
        playerRef.current = player
      }
    }, 250)

    return () => {
      if (sdkIntervalRef.current) clearInterval(sdkIntervalRef.current)
      if (progressIntervalRef.current) clearInterval(progressIntervalRef.current)
      if (playerRef.current?.destroy) {
        playerRef.current.destroy()
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // React to videoId / startSeconds changes (re-play current slice)
  const isFirstRender = useRef(true)
  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false
      return
    }
    if (playerRef.current && typeof playerRef.current.loadVideoById === 'function') {
      playSlice(playerRef.current, videoId, startSeconds, endSeconds)
      playerRef.current.seekTo(startSeconds ?? 0, true)
      startProgress()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [videoId, startSeconds])

  // React to halfScreen changes — adjust iframe CSS classes
  useEffect(() => {
    const iframe = document.querySelector(`#${PLAYER_ELEMENT_ID}`)
    if (iframe) {
      if (halfScreen) {
        iframe.classList.remove(css.fullScreen)
        iframe.classList.add(css.halfScreen)
      } else {
        iframe.classList.remove(css.halfScreen)
        iframe.classList.add(css.fullScreen)
      }
    }
  }, [halfScreen])

  return (
    <div
      id={PLAYER_ELEMENT_ID}
      className={`${css.player} ${halfScreen ? css.halfScreen : css.fullScreen} ${className || ''}`}
    />
  )
})

export default Player

// src/components/player/Player.vue
<template>
  <div
    :id="playerElementId"
    :class="[
      css.player,
      { [css.fullScreen]: !halfScreen, [css.halfScreen]: halfScreen },
    ]"
  />
</template>

<script>
import css from "./Player.module.css";
const PLAYER_ELEMENT_ID = "yt-player";
const PLAYER_STATE = {
  UNSTARTED: -1,
  ENDED: 0,
  PLAYING: 1,
  PAUSED: 2,
  BUFFERING: 3,
  VIDEO_CUED: 5,
};

export default {
  props: {
    videoId: {
      type: String,
      required: true,
    },
    startSeconds: {
      type: Number,
    },
    endSeconds: {
      type: Number,
    },
    halfScreen: {
      type: Boolean,
      default: false,
    },
  },
  data: function() {
    return {
      css,
      player: null,
      playerElementId: PLAYER_ELEMENT_ID,
      progressInterval: undefined,
    };
  },

  created() {
    this.loadSdk();

    const interval = setInterval(() => {
      if (this.checkSdkLoaded()) {
        this.initializePlayer();

        clearInterval(interval);
      } else {
        console.log("player not ready yet");
      }
    }, 250);
  },

  mounted() {
    this.adjustPlayerSize();
  },

  beforeDestroy() {
    if (this.player && this.player.destroy) {
      this.player.destroy();
    }
  },

  methods: {
    loadSdk() {
      const tag = document.createElement("script");
      const firstScriptTag = document.getElementsByTagName("script")[0];
      tag.src = "https://www.youtube.com/iframe_api";
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    },

    checkSdkLoaded() {
      if (!window.YT || !window.YT.Player) {
        return false;
      }

      return true;
    },

    initializePlayer() {
      const playerOptions = {
        events: {
          onReady: this.onReady,
          onError: this.onError,
          onStateChange: this.onStateChange,
          onPlaybackQualityChange: () => {},
          onPlaybackRateChange: () => {},
          onApiChange: () => {},
        },
      };
      this.player = new window.YT.Player(this.playerElementId, playerOptions);
    },

    onReady() {
      this.playCurrentSlice();
      this.$emit("ready");
    },

    onError(error) {
      this.$emit("error", this.videoId);
      console.error(this.videoId, error);
    },

    onEnded() {
      this.$emit("ended");
    },

    onPlaying() {
      this.$emit("playing");
    },

    onPaused() {
      this.$emit("paused");
    },

    onStateChange(event) {
      switch (event.data) {
        case PLAYER_STATE.UNSTARTED:
          break;
        case PLAYER_STATE.ENDED:
          this.onEnded();
          break;
        case PLAYER_STATE.PLAYING:
          this.onPlaying();
          break;
        case PLAYER_STATE.PAUSED:
          this.onPaused();
          break;
        case PLAYER_STATE.BUFFERING:
          break;
        case PLAYER_STATE.VIDEO_CUED:
          break;
        default:
        // unknown player state reported
      }
    },
    play() {
      this.player.playVideo();
    },
    pause() {
      this.player.pauseVideo();
    },
    stop() {
      this.player.stopVideo();
    },
    seek(seconds, allowSeekAhead = true) {
      this.player.seekTo(seconds, allowSeekAhead);
    },
    mute() {
      this.player.mute();
    },
    unmute() {
      this.player.unMute();
    },
    isMuted() {
      return this?.player?.isMuted ? this.player.isMuted() : false;
    },
    // set volume =>  0 - 100
    setVolume(volume) {
      this.player.setVolume(volume);
    },
    getVolume() {
      return this?.player?.getVolume ? this.player.getVolume() : 0;
    },
    getVideoLoadedFraction() {
      return this.player.getVideoLoadedFraction();
    },
    getPlayerState() {
      return this.player.getPlayerState();
    },
    getCurrentTime() {
      return this.player.getCurrentTime();
    },
    getDuration() {
      return this.player.getDuration();
    },
    getVideoUrl() {
      return this.player.getVideoUrl();
    },
    getIframe() {
      return this.player.getIframe();
    },
    destroy() {
      this.player.destroy();
    },
    playSlice(videoSlice) {
      const { videoId, startSeconds = 0, endSeconds } = videoSlice;
      const apiOptions = { videoId, startSeconds };

      if (endSeconds) {
        apiOptions.endSeconds = endSeconds;
      }

      this.player.loadVideoById(apiOptions);
    },

    playCurrentSlice() {
      this.playSlice({
        videoId: this.videoId,
        startSeconds: this.startSeconds,
        endSeconds: this.endSeconds,
      });

      // Force correct second once again!
      // Youtube stores last played timestamps in localstorage or session somewhere
      // and tries to resume the video on that part
      this.seek(this.startSeconds);

      this.progress();
    },

    updateTiming() {
      this.$emit("duration", this.getDuration() ?? 0);
      this.$emit("currentTime", this.getCurrentTime() ?? 0);
    },

    progress() {
      clearInterval(this.progressInterval);
      this.progressInterval = setInterval(this.updateTiming.bind(this), 500);
    },

    adjustPlayerSize() {
      const iframe = document.querySelector(`#${PLAYER_ELEMENT_ID}`);

      // original div is replaced with an iframe so we need to update it's class when this option changes
      if (this.halfScreen) {
        iframe.classList.remove(css.fullScreen);
        iframe.classList.add(css.halfScreen);
      } else {
        iframe.classList.remove(css.halfScreen);
        iframe.classList.add(css.fullScreen);
      }
    },
  },

  watch: {
    videoId() {
      this.playCurrentSlice();
    },
    startSeconds() {
      this.playCurrentSlice();
    },
    halfScreen() {
      this.adjustPlayerSize();
    },
  },
};
</script>
